# Generated by Django 5.1.2 on 2025-01-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_hideprice',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
