# Generated by Django 5.1.2 on 2025-01-09 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_product_hideprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veriation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Veriation_category', models.CharField(choices=[('color', 'color'), ('size', 'size')], max_length=100)),
                ('Veriation_value', models.CharField(max_length=100)),
                ('creates_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
