# Generated by Django 5.1.2 on 2025-01-11 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_veriation_category_veriation_veriation_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veriation',
            old_name='veriation_category',
            new_name='Veriation_category',
        ),
        migrations.RenameField(
            model_name='veriation',
            old_name='veriation_value',
            new_name='Veriation_value',
        ),
    ]
