# Generated by Django 5.1.4 on 2025-01-02 04:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_creates_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='creates_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
