# Generated by Django 5.1.4 on 2025-01-02 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_creates_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_detail',
        ),
    ]
