# Generated by Django 5.1.4 on 2025-01-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_product_product_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_detail',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
