# Generated by Django 5.1.2 on 2025-01-04 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='session_id',
            new_name='cart_id',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='created_at',
            new_name='create_at',
        ),
    ]
