# Generated by Django 5.1.2 on 2025-01-17 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0009_cartitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
